// Generated by scripts/apply-legacy-product-route-evidence.mjs.
// Edit config/legacy-product-route-evidence.json through the capture pipeline instead.
export const LEGACY_PRODUCT_ROUTES = Object.freeze([
	{
		path: '/product/a-b-hiv/',
		productId: 28,
	},
	{
		path: '/product/amylase-serum/',
		productId: 44,
	},
	{
		path: '/product/anemia-panel/',
		productId: 34,
	},
	{
		path: '/product/anti-extractable-nuclear-a-g/',
		productId: 45,
	},
	{
		path: '/product/antinuclear-antibody-ana/',
		productId: 46,
	},
	{
		path: '/product/basic-food-panel/',
		productId: 16,
	},
	{
		path: '/product/basic-sexual-health-panel/',
		productId: 30,
	},
	{
		path: '/product/basic-wellness/',
		productId: 32,
	},
	{
		path: '/product/blood-10-panel-drug-test/',
		productId: 119,
	},
	{
		path: '/product/blood-5-panel-drug-test/',
		productId: 118,
	},
	{
		path: '/product/blood-etg/',
		productId: 100,
	},
	{
		path: '/product/booking-consultation/',
		productId: 111,
	},
	{
		path: '/product/c-reactive-protein-crp/',
		productId: 55,
	},
	{
		path: '/product/cancer-antigen-125-ca-125/',
		productId: 47,
	},
	{
		path: '/product/candida-virus-a-b-igg/',
		productId: 48,
	},
	{
		path: '/product/carcinoembryonic-antigen-cea/',
		productId: 49,
	},
	{
		path: '/product/cardiac-risk-and-heart-health-panel/',
		productId: 93,
	},
	{
		path: '/product/celiac-disease-a-b-screen/',
		productId: 50,
	},
	{
		path: '/product/chlamydia/',
		productId: 29,
	},
	{
		path: '/product/coc-12-panel-drug-test/',
		productId: 115,
	},
	{
		path: '/product/coc-5-panel-drug-test/',
		productId: 114,
	},
	{
		path: '/product/coenzyme-q10/',
		productId: 51,
	},
	{
		path: '/product/complete-blood-count-cbc/',
		productId: 52,
	},
	{
		path: '/product/comprehensive-combination-allergy-panel/',
		productId: 20,
	},
	{
		path: '/product/comprehensive-metabolic-panel-cmp/',
		productId: 53,
	},
	{
		path: '/product/comprehensive-testing-panel/',
		productId: 12,
	},
	{
		path: '/product/comprehensive-thyroid-wellness-panel/',
		productId: 2,
	},
	{
		path: '/product/cortisol/',
		productId: 54,
	},
	{
		path: '/product/covid-19-pcr/',
		productId: 99,
	},
	{
		path: '/product/cyclic-citrullinated-peptide-antibody-ccp/',
		productId: 56,
	},
	{
		path: '/product/diabetes-panels/',
		productId: 94,
	},
	{
		path: '/product/dot-drug-test/',
		productId: 26,
	},
	{
		path: '/product/epstein-barr-virus-ebv-antibodies-to-early-antigen-igg/',
		productId: 36,
	},
	{
		path: '/product/estradiol/',
		productId: 57,
	},
	{
		path: '/product/estrogen-total/',
		productId: 58,
	},
	{
		path: '/product/extractable-nuclear-antigen-antibodies-anti-ssa-anti-ssb/',
		productId: 59,
	},
	{
		path: '/product/family-health-pack/',
		productId: 35,
	},
	{
		path: '/product/fatigue-health-check/',
		productId: 31,
	},
	{
		path: '/product/ferritin/',
		productId: 60,
	},
	{
		path: '/product/fibrinogen/',
		productId: 61,
	},
	{
		path: '/product/follicle-stimulating-hormone-fsh/',
		productId: 62,
	},
	{
		path: '/product/free-thyroxine-free-t4/',
		productId: 63,
	},
	{
		path: '/product/free-triiodothyronine-free-t3/',
		productId: 64,
	},
	{
		path: '/product/fribromyalgia-health-screen-check-up/',
		productId: 1,
	},
	{
		path: '/product/gonorrhea/',
		productId: 90,
	},
	{
		path: '/product/growth-hormones/',
		productId: 86,
	},
	{
		path: '/product/hair-5-panel-drug-test/',
		productId: 116,
	},
	{
		path: '/product/hair-etg/',
		productId: 101,
	},
	{
		path: '/product/hcg-qualitative-quantitative-pregnancy/',
		productId: 98,
	},
	{
		path: '/product/hepatitis-a-hep-a/',
		productId: 40,
	},
	{
		path: '/product/hepatitis-b-surface-antigen-hep-b/',
		productId: 39,
	},
	{
		path: '/product/hepatitis-c-hep-c/',
		productId: 41,
	},
	{
		path: '/product/herpes/',
		productId: 89,
	},
	{
		path: '/product/high-sensativity-cardiac-risk/',
		productId: 3,
	},
	{
		path: '/product/hla-b27-antigen/',
		productId: 65,
	},
	{
		path: '/product/homocysteine-plasma/',
		productId: 66,
	},
	{
		path: '/product/immunization-vaccination-panel/',
		productId: 33,
	},
	{
		path: '/product/immunoglobulins-iga-igg/',
		productId: 67,
	},
	{
		path: '/product/informational-dna/',
		productId: 24,
	},
	{
		path: '/product/instant-10-13-panel-drug-test-alcohol/',
		productId: 104,
	},
	{
		path: '/product/instant-12-panel-drug-test/',
		productId: 113,
	},
	{
		path: '/product/instant-5-panel-drug-test-alcohol/',
		productId: 103,
	},
	{
		path: '/product/instant-5-panel-drug-test/',
		productId: 112,
	},
	{
		path: '/product/k2-spice-designer-testing-panel/',
		productId: 25,
	},
	{
		path: '/product/legal-dna/',
		productId: 23,
	},
	{
		path: '/product/lipase/',
		productId: 68,
	},
	{
		path: '/product/lipid-profile/',
		productId: 69,
	},
	{
		path: '/product/lyme-disease-a-b-quantitative-igm/',
		productId: 37,
	},
	{
		path: '/product/magnesium-serum/',
		productId: 70,
	},
	{
		path: '/product/male-cancer-and-tumor-marker-panel/',
		productId: 85,
	},
	{
		path: '/product/male-health-panels/',
		productId: 87,
	},
	{
		path: '/product/menopause-screening-health-check-up/',
		productId: 97,
	},
	{
		path: '/product/mma-fighters-panel/',
		productId: 83,
	},
	{
		path: '/product/mold-panel-24-allergens/',
		productId: 21,
	},
	{
		path: '/product/osteoporosis-health-screen/',
		productId: 96,
	},
	{
		path: '/product/parasite-examination-op/',
		productId: 38,
	},
	{
		path: '/product/partial-thromboplastin-time-prothrombin-test-ptt-pt/',
		productId: 71,
	},
	{
		path: '/product/pediatric-panel/',
		productId: 22,
	},
	{
		path: '/product/physical-screening/',
		productId: 43,
	},
	{
		path: '/product/prothrombin-time-international-normalized-ratio-pt-inr/',
		productId: 73,
	},
	{
		path: '/product/regional-environmental-panel/',
		productId: 17,
	},
	{
		path: '/product/renal-function-test/',
		productId: 74,
	},
	{
		path: '/product/rheumatoid-factor/',
		productId: 75,
	},
	{
		path: '/product/semen-analysis/',
		productId: 84,
	},
	{
		path: '/product/sexual-health-panels/',
		productId: 88,
	},
	{
		path: '/product/syphilis/',
		productId: 42,
	},
	{
		path: '/product/testosterone-total-test/',
		productId: 120,
	},
	{
		path: '/product/throat-culture-strep-test/',
		productId: 5,
	},
	{
		path: '/product/thyroglobulin-tgb/',
		productId: 4,
	},
	{
		path: '/product/thyroid-panel/',
		productId: 95,
	},
	{
		path: '/product/thyroid-peroxidase-antibody-tpo/',
		productId: 76,
	},
	{
		path: '/product/transferrin-serum/',
		productId: 77,
	},
	{
		path: '/product/trichomonas/',
		productId: 27,
	},
	{
		path: '/product/troponin-heart-protein-test/',
		productId: 78,
	},
	{
		path: '/product/uric-acid/',
		productId: 79,
	},
	{
		path: '/product/urine-etg/',
		productId: 102,
	},
	{
		path: '/product/varicella-zoster-v-a-b-igg/',
		productId: 80,
	},
	{
		path: '/product/vitamin-b12-folate/',
		productId: 81,
	},
	{
		path: '/product/vitamin-d25/',
		productId: 82,
	},
	{
		path: '/product/womens-cancer-tumor-maker-panel/',
		productId: 91,
	},
	{
		path: '/product/womens-health/',
		productId: 92,
	},
]);
