// Generated by scripts/apply-legacy-product-route-evidence.mjs.
// Edit config/legacy-product-route-evidence.json through the capture pipeline instead.
export const LEGACY_PRODUCT_REDIRECTS = Object.freeze([
	{
		source: '/product/a-b-hiv/',
		destination: '/testing-services/28',
	},
	{
		source: '/product/amylase-serum/',
		destination: '/testing-services/44',
	},
	{
		source: '/product/anemia-panel/',
		destination: '/testing-services/34',
	},
	{
		source: '/product/anti-extractable-nuclear-a-g/',
		destination: '/testing-services/45',
	},
	{
		source: '/product/antinuclear-antibody-ana/',
		destination: '/testing-services/46',
	},
	{
		source: '/product/basic-food-panel/',
		destination: '/testing-services/16',
	},
	{
		source: '/product/basic-sexual-health-panel/',
		destination: '/testing-services/30',
	},
	{
		source: '/product/basic-wellness/',
		destination: '/testing-services/32',
	},
	{
		source: '/product/blood-10-panel-drug-test/',
		destination: '/testing-services/119',
	},
	{
		source: '/product/blood-5-panel-drug-test/',
		destination: '/testing-services/118',
	},
	{
		source: '/product/blood-etg/',
		destination: '/testing-services/100',
	},
	{
		source: '/product/booking-consultation/',
		destination: '/testing-services/111',
	},
	{
		source: '/product/c-reactive-protein-crp/',
		destination: '/testing-services/55',
	},
	{
		source: '/product/cancer-antigen-125-ca-125/',
		destination: '/testing-services/47',
	},
	{
		source: '/product/candida-virus-a-b-igg/',
		destination: '/testing-services/48',
	},
	{
		source: '/product/carcinoembryonic-antigen-cea/',
		destination: '/testing-services/49',
	},
	{
		source: '/product/cardiac-risk-and-heart-health-panel/',
		destination: '/testing-services/93',
	},
	{
		source: '/product/celiac-disease-a-b-screen/',
		destination: '/testing-services/50',
	},
	{
		source: '/product/chlamydia/',
		destination: '/testing-services/29',
	},
	{
		source: '/product/coc-12-panel-drug-test/',
		destination: '/testing-services/115',
	},
	{
		source: '/product/coc-5-panel-drug-test/',
		destination: '/testing-services/114',
	},
	{
		source: '/product/coenzyme-q10/',
		destination: '/testing-services/51',
	},
	{
		source: '/product/complete-blood-count-cbc/',
		destination: '/testing-services/52',
	},
	{
		source: '/product/comprehensive-combination-allergy-panel/',
		destination: '/testing-services/20',
	},
	{
		source: '/product/comprehensive-metabolic-panel-cmp/',
		destination: '/testing-services/53',
	},
	{
		source: '/product/comprehensive-testing-panel/',
		destination: '/testing-services/12',
	},
	{
		source: '/product/comprehensive-thyroid-wellness-panel/',
		destination: '/testing-services/2',
	},
	{
		source: '/product/cortisol/',
		destination: '/testing-services/54',
	},
	{
		source: '/product/covid-19-pcr/',
		destination: '/testing-services/99',
	},
	{
		source: '/product/cyclic-citrullinated-peptide-antibody-ccp/',
		destination: '/testing-services/56',
	},
	{
		source: '/product/diabetes-panels/',
		destination: '/testing-services/94',
	},
	{
		source: '/product/dot-drug-test/',
		destination: '/testing-services/26',
	},
	{
		source: '/product/epstein-barr-virus-ebv-antibodies-to-early-antigen-igg/',
		destination: '/testing-services/36',
	},
	{
		source: '/product/estradiol/',
		destination: '/testing-services/57',
	},
	{
		source: '/product/estrogen-total/',
		destination: '/testing-services/58',
	},
	{
		source: '/product/extractable-nuclear-antigen-antibodies-anti-ssa-anti-ssb/',
		destination: '/testing-services/59',
	},
	{
		source: '/product/family-health-pack/',
		destination: '/testing-services/35',
	},
	{
		source: '/product/fatigue-health-check/',
		destination: '/testing-services/31',
	},
	{
		source: '/product/ferritin/',
		destination: '/testing-services/60',
	},
	{
		source: '/product/fibrinogen/',
		destination: '/testing-services/61',
	},
	{
		source: '/product/follicle-stimulating-hormone-fsh/',
		destination: '/testing-services/62',
	},
	{
		source: '/product/free-thyroxine-free-t4/',
		destination: '/testing-services/63',
	},
	{
		source: '/product/free-triiodothyronine-free-t3/',
		destination: '/testing-services/64',
	},
	{
		source: '/product/fribromyalgia-health-screen-check-up/',
		destination: '/testing-services/1',
	},
	{
		source: '/product/gonorrhea/',
		destination: '/testing-services/90',
	},
	{
		source: '/product/growth-hormones/',
		destination: '/testing-services/86',
	},
	{
		source: '/product/hair-5-panel-drug-test/',
		destination: '/testing-services/116',
	},
	{
		source: '/product/hair-etg/',
		destination: '/testing-services/101',
	},
	{
		source: '/product/hcg-qualitative-quantitative-pregnancy/',
		destination: '/testing-services/98',
	},
	{
		source: '/product/hepatitis-a-hep-a/',
		destination: '/testing-services/40',
	},
	{
		source: '/product/hepatitis-b-surface-antigen-hep-b/',
		destination: '/testing-services/39',
	},
	{
		source: '/product/hepatitis-c-hep-c/',
		destination: '/testing-services/41',
	},
	{
		source: '/product/herpes/',
		destination: '/testing-services/89',
	},
	{
		source: '/product/high-sensativity-cardiac-risk/',
		destination: '/testing-services/3',
	},
	{
		source: '/product/hla-b27-antigen/',
		destination: '/testing-services/65',
	},
	{
		source: '/product/homocysteine-plasma/',
		destination: '/testing-services/66',
	},
	{
		source: '/product/immunization-vaccination-panel/',
		destination: '/testing-services/33',
	},
	{
		source: '/product/immunoglobulins-iga-igg/',
		destination: '/testing-services/67',
	},
	{
		source: '/product/informational-dna/',
		destination: '/testing-services/24',
	},
	{
		source: '/product/instant-10-13-panel-drug-test-alcohol/',
		destination: '/testing-services/104',
	},
	{
		source: '/product/instant-12-panel-drug-test/',
		destination: '/testing-services/113',
	},
	{
		source: '/product/instant-5-panel-drug-test-alcohol/',
		destination: '/testing-services/103',
	},
	{
		source: '/product/instant-5-panel-drug-test/',
		destination: '/testing-services/112',
	},
	{
		source: '/product/k2-spice-designer-testing-panel/',
		destination: '/testing-services/25',
	},
	{
		source: '/product/legal-dna/',
		destination: '/testing-services/23',
	},
	{
		source: '/product/lipase/',
		destination: '/testing-services/68',
	},
	{
		source: '/product/lipid-profile/',
		destination: '/testing-services/69',
	},
	{
		source: '/product/lyme-disease-a-b-quantitative-igm/',
		destination: '/testing-services/37',
	},
	{
		source: '/product/magnesium-serum/',
		destination: '/testing-services/70',
	},
	{
		source: '/product/male-cancer-and-tumor-marker-panel/',
		destination: '/testing-services/85',
	},
	{
		source: '/product/male-health-panels/',
		destination: '/testing-services/87',
	},
	{
		source: '/product/menopause-screening-health-check-up/',
		destination: '/testing-services/97',
	},
	{
		source: '/product/mma-fighters-panel/',
		destination: '/testing-services/83',
	},
	{
		source: '/product/mold-panel-24-allergens/',
		destination: '/testing-services/21',
	},
	{
		source: '/product/osteoporosis-health-screen/',
		destination: '/testing-services/96',
	},
	{
		source: '/product/parasite-examination-op/',
		destination: '/testing-services/38',
	},
	{
		source: '/product/partial-thromboplastin-time-prothrombin-test-ptt-pt/',
		destination: '/testing-services/71',
	},
	{
		source: '/product/pediatric-panel/',
		destination: '/testing-services/22',
	},
	{
		source: '/product/physical-screening/',
		destination: '/testing-services/43',
	},
	{
		source: '/product/prothrombin-time-international-normalized-ratio-pt-inr/',
		destination: '/testing-services/73',
	},
	{
		source: '/product/regional-environmental-panel/',
		destination: '/testing-services/17',
	},
	{
		source: '/product/renal-function-test/',
		destination: '/testing-services/74',
	},
	{
		source: '/product/rheumatoid-factor/',
		destination: '/testing-services/75',
	},
	{
		source: '/product/semen-analysis/',
		destination: '/testing-services/84',
	},
	{
		source: '/product/sexual-health-panels/',
		destination: '/testing-services/88',
	},
	{
		source: '/product/syphilis/',
		destination: '/testing-services/42',
	},
	{
		source: '/product/testosterone-total-test/',
		destination: '/testing-services/120',
	},
	{
		source: '/product/throat-culture-strep-test/',
		destination: '/testing-services/5',
	},
	{
		source: '/product/thyroglobulin-tgb/',
		destination: '/testing-services/4',
	},
	{
		source: '/product/thyroid-panel/',
		destination: '/testing-services/95',
	},
	{
		source: '/product/thyroid-peroxidase-antibody-tpo/',
		destination: '/testing-services/76',
	},
	{
		source: '/product/transferrin-serum/',
		destination: '/testing-services/77',
	},
	{
		source: '/product/trichomonas/',
		destination: '/testing-services/27',
	},
	{
		source: '/product/troponin-heart-protein-test/',
		destination: '/testing-services/78',
	},
	{
		source: '/product/uric-acid/',
		destination: '/testing-services/79',
	},
	{
		source: '/product/urine-etg/',
		destination: '/testing-services/102',
	},
	{
		source: '/product/varicella-zoster-v-a-b-igg/',
		destination: '/testing-services/80',
	},
	{
		source: '/product/vitamin-b12-folate/',
		destination: '/testing-services/81',
	},
	{
		source: '/product/vitamin-d25/',
		destination: '/testing-services/82',
	},
	{
		source: '/product/womens-cancer-tumor-maker-panel/',
		destination: '/testing-services/91',
	},
	{
		source: '/product/womens-health/',
		destination: '/testing-services/92',
	},
]);
