export function initialFieldValues(formKey) {
	const defaults = {
		contact: {
			firstname: '',
			lastname: '',
			email: '',
			phone: '',
			message: '',
		},
		scheduleAppointment: {
			firstname: '',
			lastname: '',
			email: '',
			phone: '',
			location: '',
			datetime: '',
			symptoms: '',
		},
		patientIntake: {
			firstname: '',
			lastname: '',
			phone: '',
			dateofbirth: '',
			email: '',
			address: '',
			city: '',
			apt: '',
			zipcode: '',
			state: '',
			may_contact_number: '',
			may_contact_email: '',
			may_forward_results: '',
			declaration_agreed: false,
			terms_agreed: false,
			digital_signature: '',
		},
		covidScreening: {
			firstname: '',
			lastname: '',
			phone: '',
			dateofbirth: '',
			email: '',
			address: '',
			city: '',
			apt: '',
			zipcode: '',
			state: '',
			fever_or_chills: '',
			cough: '',
			difficulty_breathing: '',
			fatigue: '',
			headache: '',
			loss_of_taste_smell: '',
			sore_throat: '',
			congestion_runny_nose: '',
			covid_exposure: '',
			vaccination_status: '',
			previous_covid_infection: '',
			declaration_agreed: false,
			terms_agreed: false,
			digital_signature: '',
		},
		prescriptionConsent: {
			firstname: '',
			lastname: '',
			phone: '',
			dateofbirth: '',
			email: '',
			address: '',
			city: '',
			apt: '',
			zipcode: '',
			state: '',
			infection: '',
			takinganymedication: '',
			currentmedications: '',
			allergic_to_medication: '',
			allergies: '',
			pregnant_or_lactating: '',
			pharmacy_name: '',
			pharmacy_phonenumber: '',
			declaration_agreed: false,
			terms_agreed: false,
			digital_signature: '',
		},
	};

	return defaults[formKey] || {};
}
